/* eslint-disable react-refresh/only-export-components -- central icon registry intentionally exports components and the Issue map */
import {
  ActivityIcon,
  ArchiveBoxIcon,
  ArrowCircleDown,
  ArrowCircleUp,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowRight,
  ArrowSquareOut,
  ArrowsDownUp,
  ArrowsInLineVertical,
  ArrowsInSimple,
  ArrowsOutLineVertical,
  ArrowsOutSimple,
  ArrowUp,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChatsCircle,
  Check,
  CheckCircle,
  CheckSquareOffset,
  ClockCounterClockwise,
  Command,
  Copy,
  Cube,
  DotsThree,
  Eye,
  EyeSlash,
  File,
  FileSearchIcon,
  Funnel,
  Gear,
  Info,
  Keyboard,
  ListChecks,
  MagnifyingGlass,
  NotePencil,
  Paperclip,
  PaperPlaneRight,
  Pencil,
  Plus,
  Scales,
  SealCheck,
  Signpost,
  Sparkle,
  SpinnerGap,
  Stop,
  UserCircle,
  UserFocus,
  Warning,
  WarningCircle,
  WarningOctagon,
  Waveform,
  X,
  XSquare,
  type Icon,
} from "@phosphor-icons/react";

export type LylIcon = Icon;

export const LYL_ICON_MAP = {
  brand: Cube,
  newIssue: Plus,
  ask: Signpost,
  decide: Scales,
  research: MagnifyingGlass,
  diagnose: Waveform,
  allIssues: ChatsCircle,
  activeIssues: ActivityIcon,
  waitingUser: UserFocus,
  counselReady: SealCheck,
  adopted: CheckSquareOffset,
  rejected: XSquare,
  reviewDue: ClockCounterClockwise,
  archived: ArchiveBoxIcon,
  search: MagnifyingGlass,
  filter: Funnel,
  sort: ArrowsDownUp,
  command: Command,
  upload: Paperclip,
  send: ArrowUp,
  stop: Stop,
  more: DotsThree,
  close: X,
  expand: ArrowsOutSimple,
  collapse: ArrowsInSimple,
  counsel: Sparkle,
  evidence: FileSearchIcon,
  history: ClockCounterClockwise,
  researchProcess: ListChecks,
  support: ArrowCircleUp,
  oppose: ArrowCircleDown,
  limit: WarningCircle,
  context: Info,
  success: CheckCircle,
  warning: Warning,
  error: WarningOctagon,
  externalLink: ArrowSquareOut,
  settings: Gear,
  user: UserCircle,
  keyboard: Keyboard,
} as const satisfies Record<string, Icon>;

export type LylIconKey = keyof typeof LYL_ICON_MAP;

export {
  ActivityIcon as Activity,
  ArchiveBoxIcon as ArchiveBox,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowRight,
  ArrowsInLineVertical,
  ArrowsInSimple,
  ArrowsOutLineVertical,
  ArrowsOutSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  Copy,
  Eye,
  EyeSlash,
  File,
  FileSearchIcon as FileSearch,
  NotePencil,
  PaperPlaneRight,
  Pencil,
  Plus,
  SpinnerGap,
  X,
};
